# Menu driven for database project
def menu():
    print("-" * 50)
    print("\t1.Fetch CategoryMaster")
    print("\t2.Fetch SubCategoryMaster")
    print("\t3.Fetch StocksMaster")
    print("\t4.Fetch Stock details based on single/Multiple Stock Code using 3 tables")
    print("\t5.Insert Stock Code")
    print("\t6.Update Record")
    print("\t7.Delete Record")
    print("\t8.Insert data from csv file")
    print("\t9.Fetch Stock details based on single/Multiple Stock Code using stocksMaster and sectorMaster")
    print("\t10.Fetch Stock details based on single/Multiple Stock Code using Oracle Join")
    print("\t11.Exit")
    print("-" * 50)
